import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')

test('removes obsolete dynamic menu route handling', () => {
  const permission = read('../src/store/modules/permission.js')
  const menu = read('../src/views/system/menu/index.vue')
  const appMain = read('../src/layout/components/AppMain.vue')
  const tagsView = read('../src/store/modules/tagsView.js')
  const router = read('../src/router/index.js')
  const sidebarItem = read('../src/layout/components/Sidebar/SidebarItem.vue')
  const topNav = read('../src/layout/components/TopNav/index.vue')
  const topBar = read('../src/layout/components/TopBar/index.vue')
  const headerSearch = read('../src/components/HeaderSearch/index.vue')
  const rightToolbar = read('../src/components/RightToolbar/index.vue')

  assert.match(permission, /import Layout from ['"]@\/layout\/index['"]/)
  assert.doesNotMatch(permission, /normalizeBackendRoutes/)
  assert.match(permission, /handleTree/)
  assert.match(permission, /function filterAsyncRouter\(asyncRouterMap, root = true\)/)
  assert.match(permission, /const routerRoute = \{ \.\.\.route \}/)
  assert.match(permission, /routerRoute\.name = routerRoute\.routeName/)
  assert.match(permission, /routerRoute\.path = root && !routePath\.startsWith\(['"]\/['"]\)/)
  assert.match(permission, /routerRoute\.component = loadView\(routerRoute\.vueComponentPath\)/)
  assert.match(permission, /routerRoute\.component = Layout/)
  assert.match(permission, /routerRoute\.meta = \{/)
  assert.doesNotMatch(permission, /routerRoute\.visible\s*(?:={2,3}|!={1,2})/)
  assert.doesNotMatch(permission, /routerRoute\.hidden/)
  assert.doesNotMatch(router, /hidden:/)
  assert.match(sidebarItem, /v-if="item\.visible"/)
  assert.match(sidebarItem, /if \(!item\.visible\)/)
  assert.match(topNav, /if \(menu\.visible\)/)
  assert.match(topBar, /filter\(\(f\) => f\.visible\)/)
  assert.match(headerSearch, /if \(!r\.visible\)/)
  assert.doesNotMatch(permission, /visible\s*(?:={2,3}|!={1,2})/)
  assert.doesNotMatch(sidebarItem, /visible\s*(?:={2,3}|!={1,2})/)
  assert.doesNotMatch(topNav, /visible\s*(?:={2,3}|!={1,2})/)
  assert.doesNotMatch(topBar, /visible\s*(?:={2,3}|!={1,2})/)
  assert.doesNotMatch(headerSearch, /visible\s*(?:={2,3}|!={1,2})/)
  assert.match(rightToolbar, /if \(!props\.columns\[item\]\.visible\)/)
  assert.match(rightToolbar, /if \(!props\.columns\[key\]\.visible\)/)
  assert.doesNotMatch(rightToolbar, /visible\s*(?:={2,3}|!={1,2})/)
  assert.doesNotMatch(sidebarItem, /item\.hidden/)
  assert.doesNotMatch(topNav, /menu\.hidden/)
  assert.doesNotMatch(topBar, /!f\.hidden/)
  assert.doesNotMatch(headerSearch, /r\.hidden/)
  assert.doesNotMatch(permission, /route\.component = loadView\(route\.component\)/)
  assert.doesNotMatch(permission, /ParentView|InnerLink|filterChildren|component === ['"]Layout['"]|component === ['"]ParentView['"]|component === ['"]InnerLink['"]/)
  assert.doesNotMatch(menu, /isFrame|form\.query|外链/)
  assert.match(menu, /row-key="id"/)
  assert.match(menu, /proxy\.handleTree\(response\.data, ["']id["']\)/)
  assert.match(menu, /v-model="form\.routePath"/)
  assert.match(menu, /v-model="form\.vueComponentPath"/)
  assert.doesNotMatch(appMain, /IframeToggle|iframe-toggle|meta\.link/)
  assert.doesNotMatch(tagsView, /iframeViews|addIframeView|meta\.link/)
  assert.equal(existsSync(new URL('../src/layout/components/Sidebar/Link.vue', import.meta.url)), false)
  assert.equal(existsSync(new URL('../src/components/ParentView/index.vue', import.meta.url)), false)
  assert.equal(existsSync(new URL('../src/layout/components/InnerLink/index.vue', import.meta.url)), false)
  assert.equal(existsSync(new URL('../src/layout/components/IframeToggle/index.vue', import.meta.url)), false)
})
